FROM dart:2.18.1 AS build

# Resolve app dependencies.
WORKDIR /app
COPY pubspec.* ./
RUN dart pub get

# Copy app source code and AOT compile it.
COPY . .

# Ensure packages are still up to date if anything has changed.
RUN dart pub get --offline
RUN dart compile exe bin/backend.dart -o bin/server

# Build minimal serving image from AOT-compiled '/server' and required system
# libraries and configuration files stored in '/runtime/' from the build stage.
FROM scratch
COPY --from=build /runtime/ /
COPY --from=build /app/bin/server /
COPY specs/ /

# Start server.
EXPOSE 4466
CMD ["/server"]
